### ISSUE TITLE
Remove already banned/picked maps from ban/pickable maps

### ISSUE THREAD

**Issue by ThePooN** [WiiPlayer2/OsuSqlTool#1]
Hi,
As discussed on Discord earlier, I added banned/picked maps to the API. It will be applied at next bot's restart.

URL: http://osusql.com/api/api.php?matches
Example output:
`{"success":true,"data":[{"ladder":1,"user1":{"username":"Zexk","userid":"4364075","rating":-1,"rank":-1,"score":1},"user2":{"username":"Jzer","userid":"1361002","rating":1655.45992,"rank":272,"score":0},"mpid":"23088343","mpname":"Standard: Unranked vs. #272 - 1235","bans":[0,1,2,3],"picks":[4,5,6]}]}`

Be aware that the map ids are starting from 0 instead of 1, as on the beatmaps page. Consider that.
Next reboot is scheduled on Friday, as we'll update the mappool. You will be informed in the #announcements channel of our Discord server.

Thanks for your tool!

**Comment by WiiPlayer2** [comment]
Is now implemented in v0.2.5907.21666.

**Comment by ThePooN** [comment]
Great! (weird build numbers tho, seems like XSplit's... lol)

**Comment by WiiPlayer2** [comment]
The last two numbers are auto-generated based on the build time (second to last is days after 2000-01-01; last is seconds after midnight).

**Comment by ThePooN** [comment]
lol ok, you might want to rename them for releases tho
